.include "defs/timer_utils.inc"

;params
.equ DSENS_ECHO_TIMEOUT_LOW_MS = 60
.equ DSENS_ECHO_MIN_MS = 2
.equ DSENS_ECHO_MAX_MS = 30
.equ DSENS_ECHO_TIMEOUT_HIGH_MS = 35

;autogenerated
;timer time values
TIMUTILS_M_PSCL (DSENS_ECHO_TIMEOUT_LOW_MS + DSENS_ECHO_TIMEOUT_HIGH_MS) / 1000.0, 16, DSENS_TIM_PSCL
TIMUTILS_M_CS DSENS_TIM_PSCL, DSENS_TIM_CS
TIMUTILS_M_TOP DSENS_TIM_PSCL, DSENS_ECHO_TIMEOUT_LOW_MS / 1000.0, DSENS_TIM_TIMEOUT_LOW_TOP
TIMUTILS_M_TOP DSENS_TIM_PSCL, DSENS_ECHO_TIMEOUT_HIGH_MS / 1000.0, DSENS_TIM_TIMEOUT_HIGH_TOP_DIFF
;waveform generation mode
.equ DSENS_TIM_WGM = 4 ;clear timer on compare match A
;compare output mode
.equ DSENS_TIM_COMA = 0 ;A disabled
.equ DSENS_TIM_COMB = 0 ;B disabled
.equ DSENS_TIM_COMC = 0 ;C disabled
;input capture noise canceler
.equ DSENS_TIM_ICNC = 1 ;enabled
;input capture edge select
.equ DSENS_TIM_ICES_FALLING = 0
.equ DSENS_TIM_ICES_RISING = 1
;force output compare
.equ DSENS_TIM_FOCA = 0 ;A disabled
.equ DSENS_TIM_FOCB = 0 ;B disabled
.equ DSENS_TIM_FOCC = 0 ;C disabled
;input capture interrupt mask
.equ DSENS_TIM_ICIE_ENABLED = 1 ;enabled
.equ DSENS_TIM_ICIE_DISABLED = 0 ;disabled
;output capture match interrupt mask
.equ DSENS_TIM_OCIEA = 1 ;A enabled
.equ DSENS_TIM_OCIEB = 0 ;B disabled
.equ DSENS_TIM_OCIEC = 0 ;C disabled
;counter overflow interrupt mask
.equ DSENS_TIM_TOIE = 0 ;disabled

.macro DSENS_SR_SETUP
	;clear counter
	clr r16
	sts TCNT4L, r16
	sts TCNT4H, r16
	;set TCCRA (COMA1, COMA0, COMB1, COMB0, COMC1, COMC0, WGM1, WGM0)
	ldi r16, (DSENS_TIM_COMA << 6) | (DSENS_TIM_COMB << 4) | (DSENS_TIM_COMC << 2) | (DSENS_TIM_WGM & 0b11)
	sts TCCR4A, r16
	;set TCCRB (ICNC, ICES, [0], WGM3, WGM2, CS2, CS1, CS0)
	ldi r16, (DSENS_TIM_ICNC << 7) | (DSENS_TIM_ICES_RISING << 6) | ((DSENS_TIM_WGM & 0b1100) << 1) | (DSENS_TIM_CS)
	sts TCCR4B, r16
	;set TCCRC (FOCA, FOCB, FOCC, [0], [0], [0], [0], [0]) 
	ldi r16, (DSENS_TIM_FOCA << 7) | (DSENS_TIM_FOCB << 6) | (DSENS_TIM_FOCC << 5)
	sts TCCR4C, r16
	;set TIMSK ([0], [0], ICIE, [0], OCIEC, OCIEB, OCIEA, TOIE)
	ldi r16, (DSENS_TIM_ICIE_ENABLED << 5) | (DSENS_TIM_OCIEC << 3) | (DSENS_TIM_OCIEB << 2) | (DSENS_TIM_OCIEA << 1) | (DSENS_TIM_TOIE)
	sts TIMSK4, r16
	;set OCRA
	ldi r16, LOW( DSENS_TIM_TIMEOUT_LOW_TOP )
	sts OCR4AL, r16
	ldi r16, HIGH( DSENS_TIM_TIMEOUT_LOW_TOP )
	sts OCR4AH, r16
.endmacro

dsens_isr_ic4:
	
	reti

dsens_isr_oca4:
	reti